
spring:
  application:
    name: feign
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka


#ribbon通用配置对所有的都有效
ribbon:
  ConnectTimeout: 1000
  RredTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  
  
#ribbon针对item-server的配置
item-server:
  ribbon:
    MaxAutoRetries: 1

    
    
#feign继承了ribbon和hystrix，默认不启用hystrix


#启用hystrix
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
            